### ISSUE TITLE
masks3d.scad: Minor inconsistency in rounding_angled_edge_mask() arguments.

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1069]
rounding_edge_mask() accepts either h or l as an argument.

rounding_angled_edge_mask() accepts only h.

(...with apologies to Ralph Waldo Emerson.)

**Comment by adrianVmariano** [comment]
I've been trying to make it so that when there's a length/height that any of l/h/length/height work.  (This is partly the fault of base openscad for having inconsistent args between its modules.)  Somehow I missed this file when I went through to apply this, so I have done it now.  Also fixed missing default on teardrops.
