### ISSUE TITLE
Include constants by default (and compiler?)

### ISSUE THREAD

**Issue by sej7278** [revarbat/BOSL2#3]
I don't know if its an OpenSCAD limitation, but  do we have to include constants.scad when all of the used modules already do that?

```
include <BOSL/constants.scad>
use <BOSL/transforms.scad>
use <BOSL/shapes.scad>
use <BOSL/threading.scad>
use <BOSL/masks.scad>
```

Also, what about a sort of "compiler"? For example when uploading to Thingiverse we can't use the Customizer function as they don't have the BOSL library on their servers, so could we have a compiler to pull in all of the functions and append it to your main scad file (and remove the use/include statements?)

**Comment by revarbat** [comment]
If you look, BOSL2 dropped all use of `use` due to OpenSCAD bugs.  Now you just need to `include <BOSL2/std.scad>` to get the commonly used libfiles included, and only need to add extra file specific includes for less common libfiles.  Check the top of the wiki pages for each libfile's docs.

The idea of a compiler is a good idea, but may be complicated to implement.  I'll think on it.
