### ISSUE TITLE
Using BOSL2 and getting the thread "depth" to match.

### ISSUE THREAD

**Issue by stillpointx** [revarbat/BOSL2#619]
Using BOSL2 and getting the thread "depth" to match.

I'm having trouble getting my thread "depth" to match up I'm trying to get it to be 2.16mm (4) but when measured (Using Blender it's 1.25mm)

Here's my process:

Measure Original bottle top:
1) Measure OUTSIDE of bottle top (no Threads)
     **39.34mm**
2) Measure OUTSIDE of Bottle top (include all Threads)
     **41.5mm**
3) Measure bottle top height
     **10mm**
4) Minus Threads number from no Threads number gets the length of thread
     **41.5-39.34 = 2.16mm** thread length (note this number doesn't match when imported into blender which ends up being **1.25mm**)
     
![image](https://user-images.githubusercontent.com/28985314/128705242-4fc162f9-476f-4cd0-aa45-202c1a707cf3.png)

include <BOSL2/std.scad>
include <BOSL2/threading.scad>
pitch = (2.16); //pitch Distance between threads. Default: 2mm/thread 

depth_a = pitch * cos(30)*5/8; 

// d Inside base diameter of threads. Default: 10

thread_helix(d=39.34, starts=2, twist=190,profile = [
 [-5/16, 0           ],
 [-1/16, depth_a/pitch ],
 [ 1/16, depth_a/pitch ],
 [ 6/16, 0           ],
], higbee=3, $fn=72);
       
An idea how to fix this correctly?

**Comment by adrianVmariano** [comment]
You've got depth set to 1.169.  You have set your pitch to 2.16 but not informed the threading module of this, so that means your pitch is actually 2.0.  

So the expected result is that you'll get a depth equal to what you requested (1.17) but multiplied by the discrepancy between actual pitch and the pitch you assumed when you made your profile, so 1.17*2.16/2=1.26.  

I imagine that if you set depth to 2.16 that would help.  But you also need to determine the actual pitch of your threads, which it's not clear you have done.
