### ISSUE TITLE
[BUG] rounding of cuboid edges seems off

### ISSUE THREAD

**Issue by Donnyvdm** [revarbat/BOSL2#971]
First off, thank you for this wonderful library. I realise BOSL2 is still in beta, but it's making me much more productive already. Well done!
I will try to report any issues that I find while testing, but if this is not the right time/channel (perhaps because some areas are still in active development), please let me know.

**Describe the bug**
When applying rounding to the edges of a cuboid with half the width of the axis length, I expect a fully rounded object. Instead there still seems to be a flat section between the rounded edges.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>

$fn=256;

cuboid([0.5, 0.5, 1], rounding=0.25, edges="Z");
```

**Expected behavior**
I expect the above cuboid to be equivalent to a `cylinder(d=0.5, h=1)`

**Screenshots**
<img width="287" alt="image" src="https://user-images.githubusercontent.com/4202651/196555572-d400b35a-8886-4f17-95e1-117daa48bc27.png">

**Additional context**
- OpenSCAD Version: 2021.01 on Windows 11
- Other libraries used: None

**Comment by adrianVmariano** [comment]
Something is definitely wrong there.   Interestingly, if you round all the edges it produces the expected result (sphere).  Look what happens if you round all but the TOP.  View from bottom.  You get a nice hemisphere and then it goes wonky.  

![image](https://user-images.githubusercontent.com/26014420/196583628-cb025def-2f16-4c69-b1b1-e70a710154a4.png)


This is the right place to post bug reports, wishes for features, suggestions for changes to the interface, anything that you think would make BOSL2 better.   We're hoping to nail things down soon, which means the window for big changes to the interface will close.
